// Auto-generated by update_data.py — do not edit manually.
// Run update_data.py to refresh when new characters are added.

export const CHARACTERS = [
    {
        id: "1001", name: "March 7th", rarity: 4,
        path: "Preservation", element: "Ice",
        icon: "icon/character/1001.png", portrait: "image/character_portrait/1001.png",
        baseStats: { hp: 1058, atk: 512, def: 573, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "Ice DMG": 0.224, "DEF%": 0.225, "Effect RES": 0.1 }
    },
    {
        id: "1002", name: "Dan Heng", rarity: 4,
        path: "The Hunt", element: "Wind",
        icon: "icon/character/1002.png", portrait: "image/character_portrait/1002.png",
        baseStats: { hp: 882, atk: 547, def: 397, spd: 110, critRate: 0.05, critDmg: 0.5 },
        traces: { "Wind DMG": 0.224, "ATK%": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1003", name: "Himeko", rarity: 5,
        path: "Erudition", element: "Fire",
        icon: "icon/character/1003.png", portrait: "image/character_portrait/1003.png",
        baseStats: { hp: 1048, atk: 757, def: 437, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "Fire DMG": 0.224, "ATK%": 0.18, "Effect RES": 0.1 }
    },
    {
        id: "1004", name: "Welt", rarity: 5,
        path: "Nihility", element: "Imaginary",
        icon: "icon/character/1004.png", portrait: "image/character_portrait/1004.png",
        baseStats: { hp: 1125, atk: 621, def: 509, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Imaginary DMG": 0.288, "Effect RES": 0.2, "Effect Hit Rate": 0.28 }
    },
    {
        id: "1005", name: "Kafka", rarity: 5,
        path: "Nihility", element: "Lightning",
        icon: "icon/character/1005.png", portrait: "image/character_portrait/1005.png",
        baseStats: { hp: 1087, atk: 679, def: 485, spd: 100, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.56, "Effect Hit Rate": 0.36, "HP%": 0.2 }
    },
    {
        id: "1006", name: "Silver Wolf", rarity: 5,
        path: "Nihility", element: "Quantum",
        icon: "icon/character/1006.png", portrait: "image/character_portrait/1006.png",
        baseStats: { hp: 1048, atk: 640, def: 461, spd: 107, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.56, "Effect Hit Rate": 0.36, "Quantum DMG": 0.16 }
    },
    {
        id: "1008", name: "Arlan", rarity: 4,
        path: "Destruction", element: "Lightning",
        icon: "icon/character/1008.png", portrait: "image/character_portrait/1008.png",
        baseStats: { hp: 1200, atk: 600, def: 331, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Effect RES": 0.18, "HP%": 0.1 }
    },
    {
        id: "1009", name: "Asta", rarity: 4,
        path: "Harmony", element: "Fire",
        icon: "icon/character/1009.png", portrait: "image/character_portrait/1009.png",
        baseStats: { hp: 1023, atk: 512, def: 463, spd: 106, critRate: 0.05, critDmg: 0.5 },
        traces: { "Fire DMG": 0.224, "DEF%": 0.225, "CRIT Rate": 0.067 }
    },
    {
        id: "1013", name: "Herta", rarity: 4,
        path: "Erudition", element: "Ice",
        icon: "icon/character/1013.png", portrait: "image/character_portrait/1013.png",
        baseStats: { hp: 953, atk: 582, def: 397, spd: 100, critRate: 0.05, critDmg: 0.5 },
        traces: { "Ice DMG": 0.224, "DEF%": 0.225, "CRIT Rate": 0.067 }
    },
    {
        id: "1014", name: "Saber", rarity: 5,
        path: "Destruction", element: "Wind",
        icon: "icon/character/1014.png", portrait: "image/character_portrait/1014.png",
        baseStats: { hp: 1242, atk: 602, def: 655, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "Wind DMG": 0.224, "CRIT Rate": 0.12, "HP%": 0.1 }
    },
    {
        id: "1015", name: "Archer", rarity: 5,
        path: "The Hunt", element: "Quantum",
        icon: "icon/character/1015.png", portrait: "image/character_portrait/1015.png",
        baseStats: { hp: 1164, atk: 621, def: 485, spd: 105, critRate: 0.05, critDmg: 0.5 },
        traces: { "Quantum DMG": 0.224, "ATK%": 0.18, "CRIT Rate": 0.067 }
    },
    {
        id: "1101", name: "Bronya", rarity: 5,
        path: "Harmony", element: "Wind",
        icon: "icon/character/1101.png", portrait: "image/character_portrait/1101.png",
        baseStats: { hp: 1242, atk: 582, def: 534, spd: 99, critRate: 0.05, critDmg: 0.5 },
        traces: { "Wind DMG": 0.224, "CRIT DMG": 0.24, "Effect RES": 0.1 }
    },
    {
        id: "1102", name: "Seele", rarity: 5,
        path: "The Hunt", element: "Quantum",
        icon: "icon/character/1102.png", portrait: "image/character_portrait/1102.png",
        baseStats: { hp: 931, atk: 640, def: 364, spd: 115, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.56, "CRIT DMG": 0.48, "DEF%": 0.25 }
    },
    {
        id: "1103", name: "Serval", rarity: 4,
        path: "Erudition", element: "Lightning",
        icon: "icon/character/1103.png", portrait: "image/character_portrait/1103.png",
        baseStats: { hp: 917, atk: 653, def: 375, spd: 104, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "Effect Hit Rate": 0.18, "Effect RES": 0.1 }
    },
    {
        id: "1104", name: "Gepard", rarity: 5,
        path: "Preservation", element: "Ice",
        icon: "icon/character/1104.png", portrait: "image/character_portrait/1104.png",
        baseStats: { hp: 1397, atk: 543, def: 655, spd: 92, critRate: 0.05, critDmg: 0.5 },
        traces: { "Ice DMG": 0.224, "Effect RES": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1105", name: "Natasha", rarity: 4,
        path: "Abundance", element: "Physical",
        icon: "icon/character/1105.png", portrait: "image/character_portrait/1105.png",
        baseStats: { hp: 1164, atk: 476, def: 507, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "HP%": 0.28, "Effect RES": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1106", name: "Pela", rarity: 4,
        path: "Nihility", element: "Ice",
        icon: "icon/character/1106.png", portrait: "image/character_portrait/1106.png",
        baseStats: { hp: 988, atk: 547, def: 463, spd: 105, critRate: 0.05, critDmg: 0.5 },
        traces: { "Ice DMG": 0.224, "ATK%": 0.18, "Effect Hit Rate": 0.1 }
    },
    {
        id: "1107", name: "Clara", rarity: 5,
        path: "Destruction", element: "Physical",
        icon: "icon/character/1107.png", portrait: "image/character_portrait/1107.png",
        baseStats: { hp: 1242, atk: 737, def: 485, spd: 90, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Physical DMG": 0.144, "HP%": 0.1 }
    },
    {
        id: "1108", name: "Sampo", rarity: 4,
        path: "Nihility", element: "Wind",
        icon: "icon/character/1108.png", portrait: "image/character_portrait/1108.png",
        baseStats: { hp: 1023, atk: 617, def: 397, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Effect Hit Rate": 0.18, "Effect RES": 0.1 }
    },
    {
        id: "1109", name: "Hook", rarity: 4,
        path: "Destruction", element: "Fire",
        icon: "icon/character/1109.png", portrait: "image/character_portrait/1109.png",
        baseStats: { hp: 1341, atk: 617, def: 353, spd: 94, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "HP%": 0.18, "CRIT DMG": 0.133 }
    },
    {
        id: "1110", name: "Lynx", rarity: 4,
        path: "Abundance", element: "Quantum",
        icon: "icon/character/1110.png", portrait: "image/character_portrait/1110.png",
        baseStats: { hp: 1058, atk: 494, def: 551, spd: 100, critRate: 0.05, critDmg: 0.5 },
        traces: { "HP%": 0.28, "DEF%": 0.225, "Effect RES": 0.1 }
    },
    {
        id: "1111", name: "Luka", rarity: 4,
        path: "Nihility", element: "Physical",
        icon: "icon/character/1111.png", portrait: "image/character_portrait/1111.png",
        baseStats: { hp: 917, atk: 582, def: 485, spd: 103, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Effect Hit Rate": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1112", name: "Topaz & Numby", rarity: 5,
        path: "The Hunt", element: "Fire",
        icon: "icon/character/1112.png", portrait: "image/character_portrait/1112.png",
        baseStats: { hp: 931, atk: 621, def: 412, spd: 110, critRate: 0.05, critDmg: 0.5 },
        traces: { "Fire DMG": 0.224, "CRIT Rate": 0.12, "HP%": 0.1 }
    },
    {
        id: "1201", name: "Qingque", rarity: 4,
        path: "Erudition", element: "Quantum",
        icon: "icon/character/1201.png", portrait: "image/character_portrait/1201.png",
        baseStats: { hp: 1023, atk: 653, def: 441, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Quantum DMG": 0.144, "DEF%": 0.125 }
    },
    {
        id: "1202", name: "Tingyun", rarity: 4,
        path: "Harmony", element: "Lightning",
        icon: "icon/character/1202.png", portrait: "image/character_portrait/1202.png",
        baseStats: { hp: 847, atk: 529, def: 397, spd: 112, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "DEF%": 0.225, "Lightning DMG": 0.08 }
    },
    {
        id: "1203", name: "Luocha", rarity: 5,
        path: "Abundance", element: "Imaginary",
        icon: "icon/character/1203.png", portrait: "image/character_portrait/1203.png",
        baseStats: { hp: 1281, atk: 757, def: 364, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "HP%": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1204", name: "Jing Yuan", rarity: 5,
        path: "Erudition", element: "Lightning",
        icon: "icon/character/1204.png", portrait: "image/character_portrait/1204.png",
        baseStats: { hp: 1164, atk: 699, def: 485, spd: 99, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "CRIT Rate": 0.12, "DEF%": 0.125 }
    },
    {
        id: "1205", name: "Blade", rarity: 5,
        path: "Destruction", element: "Wind",
        icon: "icon/character/1205.png", portrait: "image/character_portrait/1205.png",
        baseStats: { hp: 1358, atk: 543, def: 485, spd: 97, critRate: 0.05, critDmg: 0.5 },
        traces: { "HP%": 0.56, "CRIT Rate": 0.24, "Effect RES": 0.2 }
    },
    {
        id: "1206", name: "Sushang", rarity: 4,
        path: "The Hunt", element: "Physical",
        icon: "icon/character/1206.png", portrait: "image/character_portrait/1206.png",
        baseStats: { hp: 917, atk: 564, def: 419, spd: 107, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "HP%": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1207", name: "Yukong", rarity: 4,
        path: "Harmony", element: "Imaginary",
        icon: "icon/character/1207.png", portrait: "image/character_portrait/1207.png",
        baseStats: { hp: 917, atk: 600, def: 375, spd: 107, critRate: 0.05, critDmg: 0.5 },
        traces: { "Imaginary DMG": 0.224, "HP%": 0.18, "ATK%": 0.1 }
    },
    {
        id: "1208", name: "Fu Xuan", rarity: 5,
        path: "Preservation", element: "Quantum",
        icon: "icon/character/1208.png", portrait: "image/character_portrait/1208.png",
        baseStats: { hp: 1475, atk: 466, def: 606, spd: 100, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "HP%": 0.18, "Effect RES": 0.1 }
    },
    {
        id: "1209", name: "Yanqing", rarity: 5,
        path: "The Hunt", element: "Ice",
        icon: "icon/character/1209.png", portrait: "image/character_portrait/1209.png",
        baseStats: { hp: 893, atk: 679, def: 412, spd: 109, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Ice DMG": 0.144, "HP%": 0.1 }
    },
    {
        id: "1210", name: "Guinaifen", rarity: 4,
        path: "Nihility", element: "Fire",
        icon: "icon/character/1210.png", portrait: "image/character_portrait/1210.png",
        baseStats: { hp: 882, atk: 582, def: 441, spd: 106, critRate: 0.05, critDmg: 0.5 },
        traces: { "Fire DMG": 0.224, "Break Effect": 0.24, "Effect Hit Rate": 0.1 }
    },
    {
        id: "1211", name: "Bailu", rarity: 5,
        path: "Abundance", element: "Lightning",
        icon: "icon/character/1211.png", portrait: "image/character_portrait/1211.png",
        baseStats: { hp: 1319, atk: 563, def: 485, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "HP%": 0.28, "DEF%": 0.225, "Effect RES": 0.1 }
    },
    {
        id: "1212", name: "Jingliu", rarity: 5,
        path: "Destruction", element: "Ice",
        icon: "icon/character/1212.png", portrait: "image/character_portrait/1212.png",
        baseStats: { hp: 1436, atk: 679, def: 485, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.746, "SPD": 18, "HP%": 0.2 }
    },
    {
        id: "1213", name: "Dan Heng \u2022 Imbibitor Lunae", rarity: 5,
        path: "Destruction", element: "Imaginary",
        icon: "icon/character/1213.png", portrait: "image/character_portrait/1213.png",
        baseStats: { hp: 1242, atk: 699, def: 364, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "Imaginary DMG": 0.224, "CRIT Rate": 0.12, "HP%": 0.1 }
    },
    {
        id: "1214", name: "Xueyi", rarity: 4,
        path: "Destruction", element: "Quantum",
        icon: "icon/character/1214.png", portrait: "image/character_portrait/1214.png",
        baseStats: { hp: 1058, atk: 600, def: 397, spd: 103, critRate: 0.05, critDmg: 0.5 },
        traces: { "Break Effect": 0.373, "HP%": 0.18, "Quantum DMG": 0.08 }
    },
    {
        id: "1215", name: "Hanya", rarity: 4,
        path: "Harmony", element: "Physical",
        icon: "icon/character/1215.png", portrait: "image/character_portrait/1215.png",
        baseStats: { hp: 917, atk: 564, def: 353, spd: 110, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "SPD": 9, "HP%": 0.1 }
    },
    {
        id: "1217", name: "Huohuo", rarity: 5,
        path: "Abundance", element: "Wind",
        icon: "icon/character/1217.png", portrait: "image/character_portrait/1217.png",
        baseStats: { hp: 1358, atk: 602, def: 509, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "HP%": 0.56, "Effect RES": 0.36, "SPD": 10 }
    },
    {
        id: "1218", name: "Jiaoqiu", rarity: 5,
        path: "Nihility", element: "Fire",
        icon: "icon/character/1218.png", portrait: "image/character_portrait/1218.png",
        baseStats: { hp: 1358, atk: 602, def: 509, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "Effect Hit Rate": 0.28, "Fire DMG": 0.144, "SPD": 5 }
    },
    {
        id: "1220", name: "Feixiao", rarity: 5,
        path: "The Hunt", element: "Wind",
        icon: "icon/character/1220.png", portrait: "image/character_portrait/1220.png",
        baseStats: { hp: 1048, atk: 602, def: 388, spd: 112, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "CRIT Rate": 0.12, "DEF%": 0.125 }
    },
    {
        id: "1221", name: "Yunli", rarity: 5,
        path: "Destruction", element: "Physical",
        icon: "icon/character/1221.png", portrait: "image/character_portrait/1221.png",
        baseStats: { hp: 1358, atk: 679, def: 461, spd: 94, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "HP%": 0.18, "CRIT Rate": 0.067 }
    },
    {
        id: "1222", name: "Lingsha", rarity: 5,
        path: "Abundance", element: "Fire",
        icon: "icon/character/1222.png", portrait: "image/character_portrait/1222.png",
        baseStats: { hp: 1358, atk: 679, def: 437, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "Break Effect": 0.373, "HP%": 0.18, "ATK%": 0.1 }
    },
    {
        id: "1223", name: "Moze", rarity: 4,
        path: "The Hunt", element: "Lightning",
        icon: "icon/character/1223.png", portrait: "image/character_portrait/1223.png",
        baseStats: { hp: 811, atk: 600, def: 353, spd: 111, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "ATK%": 0.18, "HP%": 0.1 }
    },
    {
        id: "1224", name: "March 7th", rarity: 4,
        path: "The Hunt", element: "Imaginary",
        icon: "icon/character/1224.png", portrait: "image/character_portrait/1224.png",
        baseStats: { hp: 1058, atk: 564, def: 441, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "CRIT DMG": 0.24, "DEF%": 0.125 }
    },
    {
        id: "1225", name: "Fugue", rarity: 5,
        path: "Nihility", element: "Fire",
        icon: "icon/character/1225.png", portrait: "image/character_portrait/1225.png",
        baseStats: { hp: 1125, atk: 582, def: 558, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "SPD": 14, "Break Effect": 0.24, "HP%": 0.1 }
    },
    {
        id: "1301", name: "Gallagher", rarity: 4,
        path: "Abundance", element: "Fire",
        icon: "icon/character/1301.png", portrait: "image/character_portrait/1301.png",
        baseStats: { hp: 1305, atk: 529, def: 441, spd: 98, critRate: 0.05, critDmg: 0.5 },
        traces: { "Effect RES": 0.28, "Break Effect": 0.133, "HP%": 0.18 }
    },
    {
        id: "1302", name: "Argenti", rarity: 5,
        path: "Erudition", element: "Physical",
        icon: "icon/character/1302.png", portrait: "image/character_portrait/1302.png",
        baseStats: { hp: 1048, atk: 737, def: 364, spd: 103, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "Physical DMG": 0.144, "HP%": 0.1 }
    },
    {
        id: "1303", name: "Ruan Mei", rarity: 5,
        path: "Harmony", element: "Ice",
        icon: "icon/character/1303.png", portrait: "image/character_portrait/1303.png",
        baseStats: { hp: 1087, atk: 660, def: 485, spd: 104, critRate: 0.05, critDmg: 0.5 },
        traces: { "Break Effect": 0.373, "DEF%": 0.225, "SPD": 5 }
    },
    {
        id: "1304", name: "Aventurine", rarity: 5,
        path: "Preservation", element: "Imaginary",
        icon: "icon/character/1304.png", portrait: "image/character_portrait/1304.png",
        baseStats: { hp: 1203, atk: 446, def: 655, spd: 106, critRate: 0.05, critDmg: 0.5 },
        traces: { "DEF%": 0.35, "Imaginary DMG": 0.144, "Effect RES": 0.1 }
    },
    {
        id: "1305", name: "Dr. Ratio", rarity: 5,
        path: "The Hunt", element: "Imaginary",
        icon: "icon/character/1305.png", portrait: "image/character_portrait/1305.png",
        baseStats: { hp: 1048, atk: 776, def: 461, spd: 103, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "CRIT Rate": 0.12, "DEF%": 0.125 }
    },
    {
        id: "1306", name: "Sparkle", rarity: 5,
        path: "Harmony", element: "Quantum",
        icon: "icon/character/1306.png", portrait: "image/character_portrait/1306.png",
        baseStats: { hp: 1397, atk: 524, def: 485, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "HP%": 0.56, "CRIT DMG": 0.48, "Effect RES": 0.2 }
    },
    {
        id: "1307", name: "Black Swan", rarity: 5,
        path: "Nihility", element: "Wind",
        icon: "icon/character/1307.png", portrait: "image/character_portrait/1307.png",
        baseStats: { hp: 1087, atk: 660, def: 485, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.56, "Wind DMG": 0.288, "Effect Hit Rate": 0.2 }
    },
    {
        id: "1308", name: "Acheron", rarity: 5,
        path: "Nihility", element: "Lightning",
        icon: "icon/character/1308.png", portrait: "image/character_portrait/1308.png",
        baseStats: { hp: 1125, atk: 699, def: 437, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "CRIT DMG": 0.24, "Lightning DMG": 0.08 }
    },
    {
        id: "1309", name: "Robin", rarity: 5,
        path: "Harmony", element: "Physical",
        icon: "icon/character/1309.png", portrait: "image/character_portrait/1309.png",
        baseStats: { hp: 1281, atk: 640, def: 485, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "HP%": 0.18, "SPD": 5 }
    },
    {
        id: "1310", name: "Firefly", rarity: 5,
        path: "Destruction", element: "Fire",
        icon: "icon/character/1310.png", portrait: "image/character_portrait/1310.png",
        baseStats: { hp: 815, atk: 524, def: 776, spd: 104, critRate: 0.05, critDmg: 0.5 },
        traces: { "Break Effect": 0.746, "Effect RES": 0.36, "SPD": 10 }
    },
    {
        id: "1312", name: "Misha", rarity: 4,
        path: "Destruction", element: "Ice",
        icon: "icon/character/1312.png", portrait: "image/character_portrait/1312.png",
        baseStats: { hp: 1270, atk: 600, def: 397, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "Ice DMG": 0.224, "DEF%": 0.225, "CRIT Rate": 0.067 }
    },
    {
        id: "1313", name: "Sunday", rarity: 5,
        path: "Harmony", element: "Imaginary",
        icon: "icon/character/1313.png", portrait: "image/character_portrait/1313.png",
        baseStats: { hp: 1242, atk: 640, def: 534, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "Effect RES": 0.18, "DEF%": 0.125 }
    },
    {
        id: "1314", name: "Jade", rarity: 5,
        path: "Erudition", element: "Quantum",
        icon: "icon/character/1314.png", portrait: "image/character_portrait/1314.png",
        baseStats: { hp: 1087, atk: 660, def: 509, spd: 103, critRate: 0.05, critDmg: 0.5 },
        traces: { "Quantum DMG": 0.224, "ATK%": 0.18, "Effect RES": 0.1 }
    },
    {
        id: "1315", name: "Boothill", rarity: 5,
        path: "The Hunt", element: "Physical",
        icon: "icon/character/1315.png", portrait: "image/character_portrait/1315.png",
        baseStats: { hp: 1203, atk: 621, def: 437, spd: 107, critRate: 0.05, critDmg: 0.5 },
        traces: { "Break Effect": 0.373, "ATK%": 0.18, "HP%": 0.1 }
    },
    {
        id: "1317", name: "Rappa", rarity: 5,
        path: "Erudition", element: "Imaginary",
        icon: "icon/character/1317.png", portrait: "image/character_portrait/1317.png",
        baseStats: { hp: 1087, atk: 718, def: 461, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "SPD": 9, "Break Effect": 0.133 }
    },
    {
        id: "1321", name: "The Dahlia", rarity: 5,
        path: "Nihility", element: "Fire",
        icon: "icon/character/1321.png", portrait: "image/character_portrait/1321.png",
        baseStats: { hp: 1087, atk: 679, def: 606, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "Break Effect": 0.373, "Effect RES": 0.18, "SPD": 5 }
    },
    {
        id: "1401", name: "The Herta", rarity: 5,
        path: "Erudition", element: "Ice",
        icon: "icon/character/1401.png", portrait: "image/character_portrait/1401.png",
        baseStats: { hp: 1164, atk: 679, def: 485, spd: 99, critRate: 0.05, critDmg: 0.5 },
        traces: { "Ice DMG": 0.224, "ATK%": 0.18, "SPD": 5 }
    },
    {
        id: "1402", name: "Aglaea", rarity: 5,
        path: "Remembrance", element: "Lightning",
        icon: "icon/character/1402.png", portrait: "image/character_portrait/1402.png",
        baseStats: { hp: 1242, atk: 699, def: 485, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "Lightning DMG": 0.224, "CRIT Rate": 0.12, "DEF%": 0.125 }
    },
    {
        id: "1403", name: "Tribbie", rarity: 5,
        path: "Harmony", element: "Quantum",
        icon: "icon/character/1403.png", portrait: "image/character_portrait/1403.png",
        baseStats: { hp: 1048, atk: 524, def: 728, spd: 96, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "CRIT Rate": 0.12, "HP%": 0.1 }
    },
    {
        id: "1404", name: "Mydei", rarity: 5,
        path: "Destruction", element: "Imaginary",
        icon: "icon/character/1404.png", portrait: "image/character_portrait/1404.png",
        baseStats: { hp: 1552, atk: 427, def: 194, spd: 95, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "HP%": 0.18, "SPD": 5 }
    },
    {
        id: "1405", name: "Anaxa", rarity: 5,
        path: "Erudition", element: "Wind",
        icon: "icon/character/1405.png", portrait: "image/character_portrait/1405.png",
        baseStats: { hp: 970, atk: 757, def: 558, spd: 97, critRate: 0.05, critDmg: 0.5 },
        traces: { "Wind DMG": 0.224, "CRIT Rate": 0.12, "HP%": 0.1 }
    },
    {
        id: "1406", name: "Cipher", rarity: 5,
        path: "Nihility", element: "Quantum",
        icon: "icon/character/1406.png", portrait: "image/character_portrait/1406.png",
        baseStats: { hp: 931, atk: 640, def: 509, spd: 106, critRate: 0.05, critDmg: 0.5 },
        traces: { "SPD": 14, "Quantum DMG": 0.144, "Effect Hit Rate": 0.1 }
    },
    {
        id: "1407", name: "Castorice", rarity: 5,
        path: "Remembrance", element: "Quantum",
        icon: "icon/character/1407.png", portrait: "image/character_portrait/1407.png",
        baseStats: { hp: 1630, atk: 524, def: 485, spd: 95, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "Quantum DMG": 0.144, "CRIT DMG": 0.133 }
    },
    {
        id: "1408", name: "Phainon", rarity: 5,
        path: "Destruction", element: "Physical",
        icon: "icon/character/1408.png", portrait: "image/character_portrait/1408.png",
        baseStats: { hp: 1436, atk: 582, def: 703, spd: 94, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "CRIT Rate": 0.12, "SPD": 5 }
    },
    {
        id: "1409", name: "Hyacine", rarity: 5,
        path: "Remembrance", element: "Wind",
        icon: "icon/character/1409.png", portrait: "image/character_portrait/1409.png",
        baseStats: { hp: 1087, atk: 388, def: 631, spd: 110, critRate: 0.05, critDmg: 0.5 },
        traces: { "SPD": 14, "Effect RES": 0.18, "HP%": 0.1 }
    },
    {
        id: "1410", name: "Hysilens", rarity: 5,
        path: "Nihility", element: "Physical",
        icon: "icon/character/1410.png", portrait: "image/character_portrait/1410.png",
        baseStats: { hp: 1203, atk: 602, def: 485, spd: 102, critRate: 0.05, critDmg: 0.5 },
        traces: { "SPD": 14, "ATK%": 0.18, "Effect Hit Rate": 0.1 }
    },
    {
        id: "1412", name: "Cerydra", rarity: 5,
        path: "Harmony", element: "Wind",
        icon: "icon/character/1412.png", portrait: "image/character_portrait/1412.png",
        baseStats: { hp: 1358, atk: 621, def: 485, spd: 99, critRate: 0.05, critDmg: 0.5 },
        traces: { "Wind DMG": 0.224, "ATK%": 0.18, "HP%": 0.1 }
    },
    {
        id: "1413", name: "Evernight", rarity: 5,
        path: "Remembrance", element: "Ice",
        icon: "icon/character/1413.png", portrait: "image/character_portrait/1413.png",
        baseStats: { hp: 1319, atk: 543, def: 582, spd: 99, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "HP%": 0.18, "CRIT DMG": 0.133 }
    },
    {
        id: "1414", name: "Dan Heng \u2022 Permansor Terrae", rarity: 5,
        path: "Preservation", element: "Physical",
        icon: "icon/character/1414.png", portrait: "image/character_portrait/1414.png",
        baseStats: { hp: 1048, atk: 582, def: 776, spd: 97, critRate: 0.05, critDmg: 0.5 },
        traces: { "ATK%": 0.28, "DEF%": 0.225, "SPD": 5 }
    },
    {
        id: "1415", name: "Cyrene", rarity: 5,
        path: "Remembrance", element: "Ice",
        icon: "icon/character/1415.png", portrait: "image/character_portrait/1415.png",
        baseStats: { hp: 1397, atk: 446, def: 582, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "SPD": 9, "HP%": 0.1 }
    },
    {
        id: "1501", name: "Sparxie", rarity: 5,
        path: "Elation", element: "Fire",
        icon: "icon/character/1501.png", portrait: "image/character_portrait/1501.png",
        baseStats: { hp: 1048, atk: 640, def: 461, spd: 107, critRate: 0.05, critDmg: 0.5 },
        traces: { "Elation DMG": 0.28, "CRIT Rate": 0.12, "CRIT DMG": 0.133 }
    },
    {
        id: "1502", name: "Yao Guang", rarity: 5,
        path: "Elation", element: "Physical",
        icon: "icon/character/1502.png", portrait: "image/character_portrait/1502.png",
        baseStats: { hp: 1242, atk: 466, def: 655, spd: 101, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "SPD": 9, "Elation DMG": 0.1 }
    },
    {
        id: "1504", name: "Ashveil", rarity: 5,
        path: "The Hunt", element: "Lightning",
        icon: "icon/character/1504.png", portrait: "image/character_portrait/1504.png",
        baseStats: { hp: 854, atk: 776, def: 388, spd: 106, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT DMG": 0.373, "Lightning DMG": 0.144, "ATK%": 0.1 }
    },
    {
        id: "1505", name: "Evanescia", rarity: 5,
        path: "Elation", element: "Physical",
        icon: "icon/character/1505.png", portrait: "image/character_portrait/1505.png",
        baseStats: { hp: 1048, atk: 737, def: 461, spd: 104, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "Elation DMG": 0.18, "SPD": 5 }
    },
    {
        id: "1506", name: "Silver Wolf LV.999", rarity: 5,
        path: "Elation", element: "Imaginary",
        icon: "icon/character/1506.png", portrait: "image/character_portrait/1506.png",
        baseStats: { hp: 1048, atk: 388, def: 655, spd: 110, critRate: 0.05, critDmg: 0.5 },
        traces: { "CRIT Rate": 0.187, "SPD": 9, "Elation DMG": 0.1 }
    },
];