// Auto-generated by update_data.py — do not edit manually.
// Run update_data.py to refresh when new light cones are added.

export const LIGHT_CONES = [
    {
        id: "23034", name: "A Grounded Ascent", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23034.png",
        baseStats: { hp: 1164, atk: 476, def: 529 }
    },
    {
        id: "23045", name: "A Thankless Coronation", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23045.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "23024", name: "Along the Passing Shore", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23024.png",
        baseStats: { hp: 1058, atk: 635, def: 397 }
    },
    {
        id: "23018", name: "An Instant Before A Gaze", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23018.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23020", name: "Baptism of Pure Thought", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23020.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "23010", name: "Before Dawn", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23010.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23015", name: "Brighter Than the Sun", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23015.png",
        baseStats: { hp: 1058, atk: 635, def: 397 }
    },
    {
        id: "23003", name: "But the Battle Isn't Over", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23003.png",
        baseStats: { hp: 1164, atk: 529, def: 463 }
    },
    {
        id: "24001", name: "Cruising in the Stellar Sea", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/24001.png",
        baseStats: { hp: 953, atk: 529, def: 463 }
    },
    {
        id: "23030", name: "Dance at Sunset", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23030.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23053", name: "Dazzled by a Flowery World", rarity: 5,
        path: "Elation",
        icon: "icon/light_cone/23053.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23021", name: "Earthly Escapade", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23021.png",
        baseStats: { hp: 1164, atk: 529, def: 463 }
    },
    {
        id: "23008", name: "Echoes of the Coffin", rarity: 5,
        path: "Abundance",
        icon: "icon/light_cone/23008.png",
        baseStats: { hp: 1164, atk: 582, def: 397 }
    },
    {
        id: "24006", name: "Elation Brimming With Blessings", rarity: 5,
        path: "Elation",
        icon: "icon/light_cone/24006.png",
        baseStats: { hp: 953, atk: 529, def: 463 }
    },
    {
        id: "23048", name: "Epoch Etched in Golden Blood", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23048.png",
        baseStats: { hp: 953, atk: 635, def: 463 }
    },
    {
        id: "24004", name: "Eternal Calculus", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/24004.png",
        baseStats: { hp: 1058, atk: 529, def: 397 }
    },
    {
        id: "23039", name: "Flame of Blood, Blaze My Path", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23039.png",
        baseStats: { hp: 1376, atk: 476, def: 397 }
    },
    {
        id: "23026", name: "Flowing Nightglow", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23026.png",
        baseStats: { hp: 953, atk: 635, def: 463 }
    },
    {
        id: "23014", name: "I Shall Be My Own Sword", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23014.png",
        baseStats: { hp: 1164, atk: 582, def: 397 }
    },
    {
        id: "23031", name: "I Venture Forth to Hunt", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23031.png",
        baseStats: { hp: 953, atk: 635, def: 463 }
    },
    {
        id: "23038", name: "If Time Were a Flower", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23038.png",
        baseStats: { hp: 1270, atk: 529, def: 397 }
    },
    {
        id: "23004", name: "In the Name of the World", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23004.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23001", name: "In the Night", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23001.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23007", name: "Incessant Rain", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23007.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23023", name: "Inherently Unjust Destiny", rarity: 5,
        path: "Preservation",
        icon: "icon/light_cone/23023.png",
        baseStats: { hp: 1058, atk: 423, def: 662 }
    },
    {
        id: "23037", name: "Into the Unreachable Veil", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23037.png",
        baseStats: { hp: 953, atk: 635, def: 463 }
    },
    {
        id: "23043", name: "Lies Dance on the Breeze", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23043.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "23041", name: "Life Should Be Cast to Flames", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23041.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "23042", name: "Long May Rainbows Adorn the Sky", rarity: 5,
        path: "Remembrance",
        icon: "icon/light_cone/23042.png",
        baseStats: { hp: 1164, atk: 476, def: 529 }
    },
    {
        id: "23035", name: "Long Road Leads Home", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23035.png",
        baseStats: { hp: 953, atk: 476, def: 662 }
    },
    {
        id: "23040", name: "Make Farewells More Beautiful", rarity: 5,
        path: "Remembrance",
        icon: "icon/light_cone/23040.png",
        baseStats: { hp: 1270, atk: 529, def: 397 }
    },
    {
        id: "24005", name: "Memory's Curtain Never Falls", rarity: 5,
        path: "Remembrance",
        icon: "icon/light_cone/24005.png",
        baseStats: { hp: 1058, atk: 529, def: 397 }
    },
    {
        id: "23005", name: "Moment of Victory", rarity: 5,
        path: "Preservation",
        icon: "icon/light_cone/23005.png",
        baseStats: { hp: 1058, atk: 476, def: 595 }
    },
    {
        id: "23050", name: "Never Forget Her Flame", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23050.png",
        baseStats: { hp: 1164, atk: 529, def: 463 }
    },
    {
        id: "23017", name: "Night of Fright", rarity: 5,
        path: "Abundance",
        icon: "icon/light_cone/23017.png",
        baseStats: { hp: 1164, atk: 476, def: 529 }
    },
    {
        id: "23000", name: "Night on the Milky Way", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23000.png",
        baseStats: { hp: 1164, atk: 582, def: 397 }
    },
    {
        id: "23033", name: "Ninjutsu Inscription: Dazzling Evilbreaker", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23033.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "24000", name: "On the Fall of an Aeon", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/24000.png",
        baseStats: { hp: 1058, atk: 529, def: 397 }
    },
    {
        id: "23019", name: "Past Self in Mirror", rarity: 5,
        path: "Harmony",
        icon: "icon/light_cone/23019.png",
        baseStats: { hp: 1058, atk: 529, def: 529 }
    },
    {
        id: "23006", name: "Patience Is All You Need", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23006.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23022", name: "Reforged Remembrance", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23022.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23027", name: "Sailing Towards a Second Life", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23027.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23032", name: "Scent Alone Stays True", rarity: 5,
        path: "Abundance",
        icon: "icon/light_cone/23032.png",
        baseStats: { hp: 1058, atk: 529, def: 529 }
    },
    {
        id: "23011", name: "She Already Shut Her Eyes", rarity: 5,
        path: "Preservation",
        icon: "icon/light_cone/23011.png",
        baseStats: { hp: 1270, atk: 423, def: 529 }
    },
    {
        id: "23012", name: "Sleep Like the Dead", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23012.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "24003", name: "Solitary Healing", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/24003.png",
        baseStats: { hp: 1058, atk: 529, def: 397 }
    },
    {
        id: "23002", name: "Something Irreplaceable", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23002.png",
        baseStats: { hp: 1164, atk: 582, def: 397 }
    },
    {
        id: "24002", name: "Texture of Memories", rarity: 5,
        path: "Preservation",
        icon: "icon/light_cone/24002.png",
        baseStats: { hp: 1058, atk: 423, def: 529 }
    },
    {
        id: "23056", name: "The Finale of a Lie", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23056.png",
        baseStats: { hp: 847, atk: 635, def: 529 }
    },
    {
        id: "23046", name: "The Hell Where Ideals Burn", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23046.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "23009", name: "The Unreachable Side", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23009.png",
        baseStats: { hp: 1270, atk: 582, def: 331 }
    },
    {
        id: "23052", name: "This Love, Forever", rarity: 5,
        path: "Remembrance",
        icon: "icon/light_cone/23052.png",
        baseStats: { hp: 1270, atk: 476, def: 463 }
    },
    {
        id: "23029", name: "Those Many Springs", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23029.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "23051", name: "Though Worlds Apart", rarity: 5,
        path: "Preservation",
        icon: "icon/light_cone/23051.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23044", name: "Thus Burns the Dawn", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23044.png",
        baseStats: { hp: 953, atk: 688, def: 397 }
    },
    {
        id: "23013", name: "Time Waits for No One", rarity: 5,
        path: "Abundance",
        icon: "icon/light_cone/23013.png",
        baseStats: { hp: 1270, atk: 476, def: 463 }
    },
    {
        id: "23036", name: "Time Woven Into Gold", rarity: 5,
        path: "Remembrance",
        icon: "icon/light_cone/23036.png",
        baseStats: { hp: 1058, atk: 635, def: 397 }
    },
    {
        id: "23049", name: "To Evernight's Stars", rarity: 5,
        path: "Remembrance",
        icon: "icon/light_cone/23049.png",
        baseStats: { hp: 1164, atk: 529, def: 463 }
    },
    {
        id: "23054", name: "When She Decided to See", rarity: 5,
        path: "Elation",
        icon: "icon/light_cone/23054.png",
        baseStats: { hp: 1058, atk: 529, def: 529 }
    },
    {
        id: "23025", name: "Whereabouts Should Dreams Rest", rarity: 5,
        path: "Destruction",
        icon: "icon/light_cone/23025.png",
        baseStats: { hp: 1164, atk: 476, def: 529 }
    },
    {
        id: "23047", name: "Why Does the Ocean Sing", rarity: 5,
        path: "Nihility",
        icon: "icon/light_cone/23047.png",
        baseStats: { hp: 953, atk: 635, def: 463 }
    },
    {
        id: "23016", name: "Worrisome, Blissful", rarity: 5,
        path: "The Hunt",
        icon: "icon/light_cone/23016.png",
        baseStats: { hp: 1058, atk: 582, def: 463 }
    },
    {
        id: "23028", name: "Yet Hope Is Priceless", rarity: 5,
        path: "Erudition",
        icon: "icon/light_cone/23028.png",
        baseStats: { hp: 953, atk: 582, def: 529 }
    },
    {
        id: "21060", name: "A Dream Scented in Wheat", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21060.png",
        baseStats: { hp: 953, atk: 529, def: 397 }
    },
    {
        id: "21012", name: "A Secret Vow", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21012.png",
        baseStats: { hp: 1058, atk: 476, def: 265 }
    },
    {
        id: "21058", name: "A Trail of Bygone Blood", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21058.png",
        baseStats: { hp: 1058, atk: 529, def: 331 }
    },
    {
        id: "21045", name: "After the Charmony Fall", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21045.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "22000", name: "Before the Tutorial Mission Starts", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/22000.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21044", name: "Boundless Choreo", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21044.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21032", name: "Carve the Moon, Weave the Clouds", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21032.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21043", name: "Concert for Two", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21043.png",
        baseStats: { hp: 953, atk: 370, def: 463 }
    },
    {
        id: "21018", name: "Dance! Dance! Dance!", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21018.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21002", name: "Day One of My New Life", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21002.png",
        baseStats: { hp: 953, atk: 370, def: 463 }
    },
    {
        id: "21039", name: "Destiny's Threads Forewoven", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21039.png",
        baseStats: { hp: 953, atk: 370, def: 463 }
    },
    {
        id: "21048", name: "Dream's Montage", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21048.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21036", name: "Dreamville Adventure", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21036.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21008", name: "Eyes of the Prey", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21008.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21022", name: "Fermata", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21022.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21037", name: "Final Victor", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21037.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21038", name: "Flames Afar", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21038.png",
        baseStats: { hp: 1058, atk: 476, def: 265 }
    },
    {
        id: "22006", name: "Fly Into a Pink Tomorrow", rarity: 4,
        path: "Remembrance",
        icon: "icon/light_cone/22006.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "22002", name: "For Tomorrow's Journey", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/22002.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21051", name: "Geniuses' Greetings", rarity: 4,
        path: "Remembrance",
        icon: "icon/light_cone/21051.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21020", name: "Geniuses' Repose", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21020.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "21001", name: "Good Night and Sleep Well", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21001.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "22001", name: "Hey, Over Here", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/22001.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21061", name: "Holiday Thermae Escapade", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21061.png",
        baseStats: { hp: 1058, atk: 529, def: 331 }
    },
    {
        id: "21056", name: "In Pursuit of the Wind", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21056.png",
        baseStats: { hp: 1058, atk: 476, def: 397 }
    },
    {
        id: "21042", name: "Indelible Promise", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21042.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21041", name: "It's Showtime", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21041.png",
        baseStats: { hp: 1058, atk: 476, def: 265 }
    },
    {
        id: "21053", name: "Journey, Forever Peaceful", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21053.png",
        baseStats: { hp: 1058, atk: 370, def: 529 }
    },
    {
        id: "21009", name: "Landau's Choice", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21009.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21013", name: "Make the World Clamor", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21013.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "21004", name: "Memories of the Past", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21004.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21064", name: "Mushy Shroomy's Adventures", rarity: 4,
        path: "Elation",
        icon: "icon/light_cone/21064.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "22003", name: "Ninja Record: Sound Hunt", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/22003.png",
        baseStats: { hp: 1058, atk: 476, def: 265 }
    },
    {
        id: "21033", name: "Nowhere to Run", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21033.png",
        baseStats: { hp: 953, atk: 529, def: 265 }
    },
    {
        id: "21003", name: "Only Silence Remains", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21003.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21025", name: "Past and Future", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21025.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21014", name: "Perfect Timing", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21014.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21011", name: "Planetary Rendezvous", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21011.png",
        baseStats: { hp: 1058, atk: 423, def: 331 }
    },
    {
        id: "21046", name: "Poised to Bloom", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/21046.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21000", name: "Post-Op Conversation", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21000.png",
        baseStats: { hp: 1058, atk: 423, def: 331 }
    },
    {
        id: "21021", name: "Quid Pro Quo", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21021.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21015", name: "Resolution Shines As Pearls of Sweat", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21015.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21031", name: "Return to Darkness", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21031.png",
        baseStats: { hp: 847, atk: 529, def: 331 }
    },
    {
        id: "21024", name: "River Flows in Spring", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21024.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "21062", name: "See You at the End", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21062.png",
        baseStats: { hp: 953, atk: 529, def: 397 }
    },
    {
        id: "21047", name: "Shadowed by Night", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21047.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "21007", name: "Shared Feeling", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21007.png",
        baseStats: { hp: 953, atk: 423, def: 397 }
    },
    {
        id: "21017", name: "Subscribe for More!", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21017.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21052", name: "Sweat Now, Cry Less", rarity: 4,
        path: "Remembrance",
        icon: "icon/light_cone/21052.png",
        baseStats: { hp: 1058, atk: 529, def: 198 }
    },
    {
        id: "21010", name: "Swordplay", rarity: 4,
        path: "The Hunt",
        icon: "icon/light_cone/21010.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21006", name: "The Birth of the Self", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21006.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21040", name: "The Day The Cosmos Fell", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21040.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21057", name: "The Flower Remembers", rarity: 4,
        path: "Remembrance",
        icon: "icon/light_cone/21057.png",
        baseStats: { hp: 1058, atk: 529, def: 331 }
    },
    {
        id: "22005", name: "The Forever Victual", rarity: 4,
        path: "Harmony",
        icon: "icon/light_cone/22005.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "22004", name: "The Great Cosmic Enterprise", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/22004.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21005", name: "The Moles Welcome You", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21005.png",
        baseStats: { hp: 1058, atk: 476, def: 265 }
    },
    {
        id: "21027", name: "The Seriousness of Breakfast", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21027.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "21054", name: "The Story's Next Page", rarity: 4,
        path: "Remembrance",
        icon: "icon/light_cone/21054.png",
        baseStats: { hp: 1058, atk: 370, def: 397 }
    },
    {
        id: "21030", name: "This Is Me!", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21030.png",
        baseStats: { hp: 847, atk: 370, def: 529 }
    },
    {
        id: "21034", name: "Today Is Another Peaceful Day", rarity: 4,
        path: "Erudition",
        icon: "icon/light_cone/21034.png",
        baseStats: { hp: 847, atk: 529, def: 331 }
    },
    {
        id: "21065", name: "Today's Good Luck", rarity: 4,
        path: "Elation",
        icon: "icon/light_cone/21065.png",
        baseStats: { hp: 953, atk: 529, def: 397 }
    },
    {
        id: "21016", name: "Trend of the Universal Market", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21016.png",
        baseStats: { hp: 1058, atk: 370, def: 397 }
    },
    {
        id: "21019", name: "Under the Blue Sky", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21019.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "21055", name: "Unto Tomorrow's Morrow", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21055.png",
        baseStats: { hp: 1058, atk: 476, def: 397 }
    },
    {
        id: "21050", name: "Victory In a Blink", rarity: 4,
        path: "Remembrance",
        icon: "icon/light_cone/21050.png",
        baseStats: { hp: 847, atk: 476, def: 397 }
    },
    {
        id: "21028", name: "Warmth Shortens Cold Nights", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21028.png",
        baseStats: { hp: 1058, atk: 370, def: 397 }
    },
    {
        id: "21023", name: "We Are Wildfire", rarity: 4,
        path: "Preservation",
        icon: "icon/light_cone/21023.png",
        baseStats: { hp: 741, atk: 476, def: 463 }
    },
    {
        id: "21029", name: "We Will Meet Again", rarity: 4,
        path: "Nihility",
        icon: "icon/light_cone/21029.png",
        baseStats: { hp: 847, atk: 529, def: 331 }
    },
    {
        id: "21035", name: "What Is Real?", rarity: 4,
        path: "Abundance",
        icon: "icon/light_cone/21035.png",
        baseStats: { hp: 1058, atk: 423, def: 331 }
    },
    {
        id: "21026", name: "Woof! Walk Time!", rarity: 4,
        path: "Destruction",
        icon: "icon/light_cone/21026.png",
        baseStats: { hp: 953, atk: 476, def: 331 }
    },
    {
        id: "20014", name: "Adversarial", rarity: 3,
        path: "The Hunt",
        icon: "icon/light_cone/20014.png",
        baseStats: { hp: 741, atk: 370, def: 265 }
    },
    {
        id: "20003", name: "Amber", rarity: 3,
        path: "Preservation",
        icon: "icon/light_cone/20003.png",
        baseStats: { hp: 847, atk: 265, def: 331 }
    },
    {
        id: "20000", name: "Arrows", rarity: 3,
        path: "The Hunt",
        icon: "icon/light_cone/20000.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20005", name: "Chorus", rarity: 3,
        path: "Harmony",
        icon: "icon/light_cone/20005.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20002", name: "Collapsing Sky", rarity: 3,
        path: "Destruction",
        icon: "icon/light_cone/20002.png",
        baseStats: { hp: 847, atk: 370, def: 198 }
    },
    {
        id: "20001", name: "Cornucopia", rarity: 3,
        path: "Abundance",
        icon: "icon/light_cone/20001.png",
        baseStats: { hp: 953, atk: 265, def: 265 }
    },
    {
        id: "20007", name: "Darting Arrow", rarity: 3,
        path: "The Hunt",
        icon: "icon/light_cone/20007.png",
        baseStats: { hp: 741, atk: 370, def: 265 }
    },
    {
        id: "20006", name: "Data Bank", rarity: 3,
        path: "Erudition",
        icon: "icon/light_cone/20006.png",
        baseStats: { hp: 741, atk: 370, def: 265 }
    },
    {
        id: "20010", name: "Defense", rarity: 3,
        path: "Preservation",
        icon: "icon/light_cone/20010.png",
        baseStats: { hp: 953, atk: 265, def: 265 }
    },
    {
        id: "20008", name: "Fine Fruit", rarity: 3,
        path: "Abundance",
        icon: "icon/light_cone/20008.png",
        baseStats: { hp: 953, atk: 318, def: 198 }
    },
    {
        id: "20018", name: "Hidden Shadow", rarity: 3,
        path: "Nihility",
        icon: "icon/light_cone/20018.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20024", name: "Lingering Tear", rarity: 3,
        path: "Elation",
        icon: "icon/light_cone/20024.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20011", name: "Loop", rarity: 3,
        path: "Nihility",
        icon: "icon/light_cone/20011.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20019", name: "Mediation", rarity: 3,
        path: "Harmony",
        icon: "icon/light_cone/20019.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20012", name: "Meshing Cogs", rarity: 3,
        path: "Harmony",
        icon: "icon/light_cone/20012.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20015", name: "Multiplication", rarity: 3,
        path: "Abundance",
        icon: "icon/light_cone/20015.png",
        baseStats: { hp: 953, atk: 318, def: 198 }
    },
    {
        id: "20016", name: "Mutual Demise", rarity: 3,
        path: "Destruction",
        icon: "icon/light_cone/20016.png",
        baseStats: { hp: 847, atk: 370, def: 198 }
    },
    {
        id: "20013", name: "Passkey", rarity: 3,
        path: "Erudition",
        icon: "icon/light_cone/20013.png",
        baseStats: { hp: 741, atk: 370, def: 265 }
    },
    {
        id: "20017", name: "Pioneering", rarity: 3,
        path: "Preservation",
        icon: "icon/light_cone/20017.png",
        baseStats: { hp: 953, atk: 265, def: 265 }
    },
    {
        id: "20022", name: "Reminiscence", rarity: 3,
        path: "Remembrance",
        icon: "icon/light_cone/20022.png",
        baseStats: { hp: 635, atk: 423, def: 265 }
    },
    {
        id: "20020", name: "Sagacity", rarity: 3,
        path: "Erudition",
        icon: "icon/light_cone/20020.png",
        baseStats: { hp: 741, atk: 370, def: 265 }
    },
    {
        id: "20021", name: "Shadowburn", rarity: 3,
        path: "Remembrance",
        icon: "icon/light_cone/20021.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
    {
        id: "20009", name: "Shattered Home", rarity: 3,
        path: "Destruction",
        icon: "icon/light_cone/20009.png",
        baseStats: { hp: 847, atk: 370, def: 198 }
    },
    {
        id: "20023", name: "Sneering", rarity: 3,
        path: "Elation",
        icon: "icon/light_cone/20023.png",
        baseStats: { hp: 741, atk: 370, def: 265 }
    },
    {
        id: "20004", name: "Void", rarity: 3,
        path: "Nihility",
        icon: "icon/light_cone/20004.png",
        baseStats: { hp: 847, atk: 318, def: 265 }
    },
];